runtime:
  max_threads: 'max'  # int | 'max', where 'max' means the number of cores on pc

plotting:
  max_plotted_bcids: 100
  fit_uncertainty: False  # A bit slow
  log_plot: True  # in addition to lin

# YAML technicality: floating point numbers need the dot before 'e' and sign after 'e'
fitting:
  adaptive:
    pool:
      - [twoMuDg, mean2]
      - [dg, frac]
      - [polyG4, r4]
      - [polyG2, r2]
      - [sg, null]

    # Has no effect if parameter_limit is stricter
    parameters_significance_threshold:
      frac: [0.1, 0.9]
      r2: [-1.e+9, 1.e+9]
      r4: [-1.e+9, 1.e+9]
      r6: [-1.e+9, 1.e+9]
      mean2: [1.e-3, 1.e+9]
    chi2_threshold: 1.0e7
    require_valid: True
    require_accurate: True
    require_not_at_limit: True

  parameter_limits:
    peak: [0, 10]
    capsigma: [1.e-3, 1]
    mean: [-1.e-1, 1.e-1]
    frac: [0, 1]
    capsigma_ratio: [0, 1]
    r2: [-0.2, 0.2]
    r4: [-0.2, 0.2]
    r6: [-0.2, 0.2]
    sigma1: [0.01, 10]
    sigma2: [0.01, 10]
    mean1: [-1.e-1, 1.e-1]
    mean2: [-1.e-1, 1.e-1]

  # peak limit auto = nominal head-on rate
  parameter_initial_values:
    sg:
      peak: auto
      mean: 0
      capsigma: auto
    sgConst:
      peak: auto
      mean: 0
      capsigma: auto
      const: 0
    dg:
      peak: auto
      mean: 0
      capsigma: auto
      frac: 0.5
      capsigma_ratio: 0.9
    dgConst:
      peak: auto
      mean: 0
      capsigma: auto
      frac: 0.5
      capsigma_ratio: 0.9
      const: 0
    polyG6:
      peak: auto
      mean: 0
      capsigma: auto
      r2: 0
      r4: 0
      r6: 0
    polyG6Const:
      peak: auto
      mean: 0
      capsigma: auto
      r2: 0
      r4: 0
      r6: 0
      const: 0
    polyG4:
      peak: auto
      mean: 0
      capsigma: auto
      r2: 0
      r4: 0
    polyG4Const:
      peak: auto
      mean: 0
      capsigma: auto
      r2: 0
      r4: 0
      const: 0
    polyG2:
      peak: auto
      mean: 0
      capsigma: auto
      r2: 0
    polyG2Const:
      peak: auto
      mean: 0
      capsigma: auto
      r2: 0
      const: 0
    superG:
      peak: auto
      mean: 0
      capsigma: auto
      p: 1
    superGConst:
      peak: auto
      mean: 0
      capsigma: auto
      p: 1
      const: 0
    twoMuDg:
      A: auto
      frac: 0.5
      sigma1: auto
      sigma2: auto
      mean1: 0
      mean2: 0
