# Runtime
max_threads: 'max'  # int | 'max'

# Fits

# YAML technicality: floating point numbers need the dot before 'e'
fit_parameter_limits:
  peak: [0, null]
  capsigma: [1.e-3, 2]
  mean: [-5.e-2, 5.e-2]
  peak_ratio: [0, 1]
  capsigma_ratio: [0, null]
  #capsigma_ratio: [1, null]

# peak limit auto = nominal head-on rate
fit_parameter_initial_values:
  sg:
    peak: auto
    mean: 0
    capsigma: 0.4
  sgConst:
    peak: auto
    mean: 0
    capsigma: 0.4
    constant: 0
  dg:
    peak: auto
    mean: 0
    capsigma: 0.2
    peak_ratio: 0.5
    capsigma_ratio: 2
  dgConst:
    peak: auto
    mean: 0
    capsigma: 0.2
    peak_ratio: 0.5
    capsigma_ratio: 2
    const: 0
  polyG6:
    peak: auto
    mean: 0
    capsigma: 0.4
    r2: 0
    r4: 0
    r6: 0
  polyG6Const:
    peak: auto
    mean: 0
    capsigma: 0.4
    r2: 0
    r4: 0
    r6: 0
    const: 0
  polyG4:
    peak: auto
    mean: 0
    capsigma: 0.4
    r2: 0
    r4: 0
  polyG4onst:
    peak: auto
    mean: 0
    capsigma: 0.4
    r2: 0
    r4: 0
    const: 0
  polyG2:
    peak: auto
    mean: 0
    capsigma: 0.4
    r2: 0
  polyG2Const:
    peak: auto
    mean: 0
    capsigma: 0.4
    r2: 0
    const: 0
  superG:
    peak: auto
    mean: 0
    capsigma: 0.4
    p: 1
  superGConst:
    peak: auto
    mean: 0
    capsigma: 0.4
    p: 1
    const: 0
